### ISSUE TITLE
request: command to generate shell completion scripts

### ISSUE THREAD

**Issue by minhtrancccp** [4imothy/treegrep#11]
per title, is it possible for the completions scripts to be generated on demand instead of manually linking them from `$CARGO_HOME`?

many thanks.

**Comment by 4imothy** [comment]
Yes this is possible I will add a flag which takes the name of a shell and then prints the completion script for that shell to stdout. Is that what you were thinking of?

Something like
```zsh
> tgrep --complete zsh
#compdef tgrep

...
```

**Comment by minhtrancccp** [comment]
that sounds right for me

**Comment by 4imothy** [comment]
Sorry for taking a while but let me know if that is what you were looking for. Using code on `main` you can now do
```
tgrep --completions <shell>
```
To generate completions to stdout.
